import { Product, Category } from '@/types/product';

// ─── Local AURA product images (/public/images/products/) ────────────────────
const P = (slug: string) => `/images/products/${slug}.jpeg`;

const SHOES = {
  phantom:  P('phantom'),
  voltage:  P('voltage'),
  ghost:    P('ghost'),
  blaze:    P('blaze'),
  eclipse:  P('eclipse'),
  drift:    P('drift'),
  nova:     P('nova'),
  stealth:  P('stealth'),
  apex:     P('apex'),
  zenith:   P('zenith'),
  vortex:   P('vortex'),
  pulse:    P('pulse'),
  obsidian: P('obsidian'),
  prism:    P('prism'),
  titan:    P('titan'),
  flux:     P('flux'),
  shadow:   P('shadow'),
  cipher:   P('cipher'),
  origin:   P('origin'),
};

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Running',
    slug: 'running',
    image: P('cat-running'),
  },
  {
    id: 'cat-2',
    name: 'Lifestyle',
    slug: 'lifestyle',
    image: P('cat-lifestyle'),
  },
  {
    id: 'cat-3',
    name: 'Basketball',
    slug: 'basketball',
    image: P('cat-basketball'),
  },
  {
    id: 'cat-4',
    name: 'Limited Edition',
    slug: 'limited-edition',
    image: P('cat-limited'),
  },
];

function makeSizes(outOfStock: number[] = []): Product['sizes'] {
  return Array.from({ length: 7 }, (_, i) => {
    const size = (7 + i).toString();
    return { id: `size-${size}`, size, inStock: !outOfStock.includes(7 + i) };
  });
}

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'AURA Phantom',
    slug: 'aura-phantom',
    description: 'Disappear into the night. The Phantom fuses stealth aesthetics with cloud-like cushioning for those who move in silence.',
    price: 189.99,
    images: [SHOES.phantom],
    brand: 'AURA',
    category: categories[1],
    categoryId: 'cat-2',
    sizes: makeSizes([11]),
    colors: [
      { id: 'c1-1', name: 'Black', hex: '#000000', images: [SHOES.phantom] },
      { id: 'c1-2', name: 'White', hex: '#FFFFFF', images: [SHOES.ghost] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['new', 'bestseller'],
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'prod-2',
    name: 'AURA Voltage',
    slug: 'aura-voltage',
    description: 'Charged with energy. The Voltage delivers explosive responsiveness with a bold violet silhouette that commands the room.',
    price: 219.99,
    images: [SHOES.voltage],
    brand: 'AURA',
    category: categories[0],
    categoryId: 'cat-1',
    sizes: makeSizes([7, 13]),
    colors: [
      { id: 'c2-1', name: 'Violet', hex: '#8B5CF6', images: [SHOES.voltage] },
      { id: 'c2-2', name: 'Black', hex: '#000000', images: [SHOES.phantom] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['new'],
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-11-15'),
  },
  {
    id: 'prod-3',
    name: 'AURA Ghost',
    slug: 'aura-ghost',
    description: 'Minimal presence, maximum impact. The Ghost is a wardrobe staple built for those who keep it clean.',
    price: 199.99,
    images: [SHOES.ghost],
    brand: 'AURA',
    category: categories[1],
    categoryId: 'cat-2',
    sizes: makeSizes([9]),
    colors: [
      { id: 'c3-1', name: 'White', hex: '#FFFFFF', images: [SHOES.ghost] },
      { id: 'c3-2', name: 'Gray', hex: '#6B7280', images: [SHOES.shadow] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['bestseller'],
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2025-10-20'),
  },
  {
    id: 'prod-4',
    name: 'AURA Blaze',
    slug: 'aura-blaze',
    description: 'Set the court on fire. The Blaze features triple-density cushioning and a bold red silhouette that owns every game.',
    price: 229.99,
    comparePrice: 270,
    images: [SHOES.blaze],
    brand: 'AURA',
    category: categories[2],
    categoryId: 'cat-3',
    sizes: makeSizes([8, 12]),
    colors: [
      { id: 'c4-1', name: 'Red', hex: '#DC2626', images: [SHOES.blaze] },
      { id: 'c4-2', name: 'Black', hex: '#000000', images: [SHOES.phantom] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['new', 'bestseller'],
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2025-12-10'),
  },
  {
    id: 'prod-5',
    name: 'AURA Eclipse',
    slug: 'aura-eclipse',
    description: 'When darkness meets gold. The Eclipse is our signature limited drop for collectors who understand rarity.',
    price: 249.99,
    images: [SHOES.eclipse],
    brand: 'AURA',
    category: categories[3],
    categoryId: 'cat-4',
    sizes: makeSizes([7, 10, 13]),
    colors: [
      { id: 'c5-1', name: 'Black', hex: '#000000', images: [SHOES.eclipse] },
      { id: 'c5-2', name: 'Gold', hex: '#D4AF37', images: [SHOES.origin] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['limited', 'new'],
    createdAt: new Date('2025-12-20'),
    updatedAt: new Date('2025-12-20'),
  },
  {
    id: 'prod-6',
    name: 'AURA Drift',
    slug: 'aura-drift',
    description: 'Flow through every environment. The Drift combines breathable construction with a lightweight sole for all-day movement.',
    price: 179.99,
    images: [SHOES.drift],
    brand: 'AURA',
    category: categories[0],
    categoryId: 'cat-1',
    sizes: makeSizes([]),
    colors: [
      { id: 'c6-1', name: 'Blue', hex: '#3B82F6', images: [SHOES.drift] },
      { id: 'c6-2', name: 'White', hex: '#FFFFFF', images: [SHOES.ghost] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['bestseller'],
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-09-01'),
  },
  {
    id: 'prod-7',
    name: 'AURA Nova',
    slug: 'aura-nova',
    description: 'Born from the future. The Nova channels neon energy into a silhouette that turns every street into a runway.',
    price: 209.99,
    images: [SHOES.nova],
    brand: 'AURA',
    category: categories[1],
    categoryId: 'cat-2',
    sizes: makeSizes([8]),
    colors: [
      { id: 'c7-1', name: 'Green', hex: '#22C55E', images: [SHOES.nova] },
      { id: 'c7-2', name: 'Black', hex: '#000000', images: [SHOES.phantom] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['limited'],
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-05'),
  },
  {
    id: 'prod-8',
    name: 'AURA Stealth',
    slug: 'aura-stealth',
    description: 'All black everything. The Stealth is a monochromatic masterpiece for those who let their presence speak.',
    price: 239.99,
    images: [SHOES.stealth],
    brand: 'AURA',
    category: categories[1],
    categoryId: 'cat-2',
    sizes: makeSizes([12, 13]),
    colors: [
      { id: 'c8-1', name: 'Black', hex: '#000000', images: [SHOES.stealth] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['new'],
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2025-12-15'),
  },
  {
    id: 'prod-9',
    name: 'AURA Apex',
    slug: 'aura-apex',
    description: 'Peak performance, peak style. The Apex delivers locked-in midfoot support with a striking court-ready profile.',
    price: 259.99,
    comparePrice: 300,
    images: [SHOES.apex],
    brand: 'AURA',
    category: categories[2],
    categoryId: 'cat-3',
    sizes: makeSizes([7, 11]),
    colors: [
      { id: 'c9-1', name: 'White', hex: '#FFFFFF', images: [SHOES.apex] },
      { id: 'c9-2', name: 'Violet', hex: '#8B5CF6', images: [SHOES.voltage] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: [],
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-09-20'),
  },
  {
    id: 'prod-10',
    name: 'AURA Zenith',
    slug: 'aura-zenith',
    description: 'The summit of craftsmanship. The Zenith is a limited-edition statement piece that redefines what premium means.',
    price: 299.99,
    images: [SHOES.zenith],
    brand: 'AURA',
    category: categories[3],
    categoryId: 'cat-4',
    sizes: makeSizes([13]),
    colors: [
      { id: 'c10-1', name: 'Black', hex: '#000000', images: [SHOES.zenith] },
      { id: 'c10-2', name: 'Purple', hex: '#7C3AED', images: [SHOES.cipher] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['limited', 'new'],
    createdAt: new Date('2025-12-05'),
    updatedAt: new Date('2025-12-05'),
  },
  {
    id: 'prod-11',
    name: 'AURA Vortex',
    slug: 'aura-vortex',
    description: 'Step into the eye of the storm. The Vortex channels raw energy into a running silhouette built to break records.',
    price: 189.99,
    images: [SHOES.vortex],
    brand: 'AURA',
    category: categories[0],
    categoryId: 'cat-1',
    sizes: makeSizes([7, 8, 12, 13]),
    colors: [
      { id: 'c11-1', name: 'Orange', hex: '#F97316', images: [SHOES.vortex] },
      { id: 'c11-2', name: 'Black', hex: '#000000', images: [SHOES.phantom] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['new'],
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'prod-12',
    name: 'AURA Pulse',
    slug: 'aura-pulse',
    description: 'Feel every beat. The Pulse is engineered for the athlete who trains as hard as they perform.',
    price: 199.99,
    images: [SHOES.pulse],
    brand: 'AURA',
    category: categories[0],
    categoryId: 'cat-1',
    sizes: makeSizes([]),
    colors: [
      { id: 'c12-1', name: 'Pink', hex: '#EC4899', images: [SHOES.pulse] },
      { id: 'c12-2', name: 'White', hex: '#FFFFFF', images: [SHOES.ghost] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['bestseller'],
    createdAt: new Date('2025-08-10'),
    updatedAt: new Date('2025-08-10'),
  },
  {
    id: 'prod-13',
    name: 'AURA Obsidian',
    slug: 'aura-obsidian',
    description: 'Forged from volcanic stone. The Obsidian is a collector\'s grail — dark, dense, and devastatingly good.',
    price: 269.99,
    images: [SHOES.obsidian],
    brand: 'AURA',
    category: categories[3],
    categoryId: 'cat-4',
    sizes: makeSizes([8, 9, 12]),
    colors: [
      { id: 'c13-1', name: 'Black', hex: '#000000', images: [SHOES.obsidian] },
      { id: 'c13-2', name: 'Charcoal', hex: '#374151', images: [SHOES.stealth] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['limited'],
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2025-11-25'),
  },
  {
    id: 'prod-14',
    name: 'AURA Prism',
    slug: 'aura-prism',
    description: 'Light bends around you. The Prism captures every angle with iridescent detailing and a featherweight build.',
    price: 219.99,
    images: [SHOES.prism],
    brand: 'AURA',
    category: categories[1],
    categoryId: 'cat-2',
    sizes: makeSizes([]),
    colors: [
      { id: 'c14-1', name: 'Multi', hex: '#8B5CF6', images: [SHOES.prism] },
      { id: 'c14-2', name: 'White', hex: '#FFFFFF', images: [SHOES.ghost] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: [],
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-15'),
  },
  {
    id: 'prod-15',
    name: 'AURA Titan',
    slug: 'aura-titan',
    description: 'Dominate the paint. The Titan provides ankle-locking support and explosive responsiveness for the power player.',
    price: 249.99,
    images: [SHOES.titan],
    brand: 'AURA',
    category: categories[2],
    categoryId: 'cat-3',
    sizes: makeSizes([]),
    colors: [
      { id: 'c15-1', name: 'Gray', hex: '#6B7280', images: [SHOES.titan] },
      { id: 'c15-2', name: 'Black', hex: '#000000', images: [SHOES.stealth] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['bestseller'],
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-01'),
  },
  {
    id: 'prod-16',
    name: 'AURA Flux',
    slug: 'aura-flux',
    description: 'Constant motion, constant evolution. The Flux adapts to your pace with responsive cushioning and a fluid silhouette.',
    price: 199.99,
    images: [SHOES.flux],
    brand: 'AURA',
    category: categories[0],
    categoryId: 'cat-1',
    sizes: makeSizes([7, 12]),
    colors: [
      { id: 'c16-1', name: 'Teal', hex: '#14B8A6', images: [SHOES.flux] },
      { id: 'c16-2', name: 'Black', hex: '#000000', images: [SHOES.phantom] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: [],
    createdAt: new Date('2025-08-20'),
    updatedAt: new Date('2025-08-20'),
  },
  {
    id: 'prod-17',
    name: 'AURA Shadow',
    slug: 'aura-shadow',
    description: 'Understated excellence. The Shadow moves through the world in quiet confidence — the choice of those who know.',
    price: 229.99,
    images: [SHOES.shadow],
    brand: 'AURA',
    category: categories[1],
    categoryId: 'cat-2',
    sizes: makeSizes([]),
    colors: [
      { id: 'c17-1', name: 'Black', hex: '#000000', images: [SHOES.shadow] },
      { id: 'c17-2', name: 'Gray', hex: '#9CA3AF', images: [SHOES.obsidian] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['new'],
    createdAt: new Date('2025-12-08'),
    updatedAt: new Date('2025-12-08'),
  },
  {
    id: 'prod-18',
    name: 'AURA Cipher',
    slug: 'aura-cipher',
    description: 'Encoded with intent. The Cipher is a limited release for those who read between the lines — rare by design.',
    price: 279.99,
    images: [SHOES.cipher],
    brand: 'AURA',
    category: categories[3],
    categoryId: 'cat-4',
    sizes: makeSizes([7, 8, 13]),
    colors: [
      { id: 'c18-1', name: 'Black', hex: '#000000', images: [SHOES.cipher] },
      { id: 'c18-2', name: 'Silver', hex: '#C0C0C0', images: [SHOES.stealth] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['limited'],
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-11-10'),
  },
  {
    id: 'prod-19',
    name: 'AURA Ignite',
    slug: 'aura-ignite',
    description: 'Spark something. The Ignite is a basketball-first silhouette with the street credibility to match its court legacy.',
    price: 209.99,
    images: [SHOES.blaze],
    brand: 'AURA',
    category: categories[2],
    categoryId: 'cat-3',
    sizes: makeSizes([]),
    colors: [
      { id: 'c19-1', name: 'Red', hex: '#EF4444', images: [SHOES.blaze] },
      { id: 'c19-2', name: 'White', hex: '#FFFFFF', images: [SHOES.ghost] },
    ],
    reviews: [],
    featured: false,
    inStock: true,
    tags: ['new'],
    createdAt: new Date('2025-12-18'),
    updatedAt: new Date('2025-12-18'),
  },
  {
    id: 'prod-20',
    name: 'AURA Origin',
    slug: 'aura-origin',
    description: 'Where it all began. The Origin is a premium re-issue of our founding silhouette — crafted for the purist.',
    price: 349.99,
    images: [SHOES.origin],
    brand: 'AURA',
    category: categories[3],
    categoryId: 'cat-4',
    sizes: makeSizes([8, 9, 10, 11]),
    colors: [
      { id: 'c20-1', name: 'Cream', hex: '#FFFDD0', images: [SHOES.origin] },
      { id: 'c20-2', name: 'Brown', hex: '#92400E', images: [SHOES.drift] },
    ],
    reviews: [],
    featured: true,
    inStock: true,
    tags: ['limited', 'bestseller'],
    createdAt: new Date('2025-11-28'),
    updatedAt: new Date('2025-11-28'),
  },
];

export const featuredProducts = products.filter((p) => p.featured);

// ─── Brand story atmospheric images ──────────────────────────────────────────
export const brandImages = {
  craftsmanship: P('eclipse'),   // black/gold luxury
  urban:         P('vortex'),    // orange runner energy
  materials:     P('obsidian'),  // dark close-up
  lineup:        P('origin'),    // premium cream
};

export interface Testimonial {
  id: string;
  name: string;
  initials: string;
  rating: number;
  comment: string;
  product: string;
}

export const testimonials: Testimonial[] = [
  { id: '1', name: 'Marcus Johnson', initials: 'MJ', rating: 5, comment: 'The comfort is unreal. Best sneakers I\'ve ever owned, bar none.', product: 'AURA Phantom' },
  { id: '2', name: 'Sarah Chen', initials: 'SC', rating: 5, comment: 'These turned heads everywhere I went. The quality is genuinely premium.', product: 'AURA Voltage' },
  { id: '3', name: 'David Park', initials: 'DP', rating: 5, comment: 'Worth every penny. The attention to detail is absolutely insane.', product: 'AURA Eclipse' },
  { id: '4', name: 'Elena Rodriguez', initials: 'ER', rating: 4, comment: 'Beautiful design and incredibly comfortable for all-day wear.', product: 'AURA Ghost' },
  { id: '5', name: 'James Wright', initials: 'JW', rating: 5, comment: 'The limited edition colorway is a work of art. Never taking them off.', product: 'AURA Zenith' },
];
